#!/bin/bash

# Author: Andres Abril
# © 2017, Emerson Electric Co 
# Description: installation sequence

cd ..
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
npm install -g forever
npm install

exit 0